# Site settings
title: the unknown developer podcast
header-img: img/post-bg-005.jpg
email: theunknowndeveloper.podcast@gmail.com
copyright_name: the-unknown-developer-podcast
description: "knowledge only real when shared"
baseurl: ""
url: "http://theunknowndeveloperpodcast.github.io"
github_username:  the-unknown-developer-podcast
show_profile_link: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
